interface Env {
  SUPABASE_SERVICE_ROLE_KEY: string;
  TELEGRAM_BOT_TOKEN: string;
  TELEGRAM_ALLOWED_USERS: string;
  TELEGRAM_WEBHOOK_SECRET: string;
  HERMES_DASHBOARD_API_SECRET: string;
  GEMINI_API_KEY: string;
  GROQ_API_KEY: string;
}
